### ISSUE TITLE
Compiler Error from refernce or include header

### ISSUE THREAD

**Issue by ghost** [philipp-eger-dev/Spectrum#1]
Hi
I am getting the following error
1. The name 'PDFDoc' does not exist in the current context
2. The type or namespace name 'PDFDoc' could not be found (are you missing a using directive or an assembly reference?) 

from the following code

using (PDFDoc doc = PDFDoc.Open(file.FilePath))
                {
                    doc.Ocr(OcrMode.Tesseract, tesseractLanguageString, WriteTextMode.Word, null);
                    sourcePDFFile = doc.ReaderPDF;

```
                outputPath = CreateFileOutputPath(file.FilePath, outputDirectory, replaceSourceFile);

                if (File.Exists(sourcePDFFile))
                {
                    File.Copy(sourcePDFFile, outputPath, true);
                }
            }
```

How to fix the issue? 
Kindly do the help.

Regards
Guna

**Comment by philipp-eger-dev** [comment]
PDFDoc is defined in HOcr2Pdf assembly. Do you have a correct reference to this assembly? 
It should look like this:

![image](https://cloud.githubusercontent.com/assets/12989198/9383728/819a7428-474b-11e5-88b3-22c0b28188d8.png)

Maybe you should get the HOcr2PDF project (https://hocrtopdf.codeplex.com/), compile it on your own and add the new assembly to the Spectrum-Project. I had to do it this way because HOcr2PDF does provide an old assembly. 

Hope this helps.

Regards
Philipp

**Comment by ghost** [comment]
Hi Sir

Thanks for the information. I have successfully build the project without any error.
Yesterday I have sent the mail to you (philipp.eger.dev@outlook.com) regarding another issue(Output pdf file is not text searchable file its look like copy of input file). 

I am posting my mail content here...

Hope you are doing great.

I am Guna from India.

I am using your spectrum - searchable PDF creator. I am able to build the application without any error.

If i give pdf file as input , i got output pdf file but the output pdf file is not searchable PDF. Its like a copy of input file.Attached input and output files.

And also while processing the input file i got following 3 files  in the C:\Users\USER\AppData\Local\Temp\Clock.hocr folder.
1. pdf file. 2. bmp file and OCR text file. attached those files also.

Am i doing anything wrong? I need output pdf file as text searchable PDF.

How can i get it. I am very urgent of this one.

Kindly do the needful.

Looking forward your reply.

I can't attach pdf and zip files sir.

I have sent mail tou . you can check it your mail inbox.

Regards
Guna

**Comment by philipp-eger-dev** [comment]
Hi Guna,

sorry but I did not receive an E-Mail. The mail address you posted is correct. May you try to send your mail again?

If it is a urgent case, I can send you a ZIP-File with the executables which I use for testing. In any case they should work. Can you post your E-Mail address here?

In some special cases the application does not seem to be able to copy the searchable text file from temporary folder to the correct output directory. The temporary directory is your Clock.HOCR directory in %localappdata%. 

You should see a PDF with searchable text in this directory. Maybe you should debug through the code und stop after the doc.OCR()-method to ensure that temporary files are not deleted.

Then you can copy the file manually. Not very nice but if it is really urgent I think this is a good workaround.

Regards
Philipp

**Comment by ghost** [comment]
Hi Sir.

Thanks for your quick reply.

My mail id - mail2vguna@gmail.com

I did not get failure delivery. i will resend the mail sir.

Regards
Guna

**Comment by ghost** [comment]
Hi sir

You can check in junk mails.

Regards
Guna

**Comment by ghost** [comment]
Hi Sir

If you don't mind can you give your skype id, we can have skype call and desktop sharing?

Looking forward your reply sir.

Regards
Guna

**Comment by philipp-eger-dev** [comment]
I sent you an Email with the executables working for me.

**Comment by ghost** [comment]
Thank you sir. I will check and get back to you. 

Also i am getting following run time error while run the application

The process cannot access the file '1j01nyzh.jb2.pdf' because it is being used by another process.

line:             Directory.Delete(CurrentJobFolder, true);

Regards
Guna

**Comment by ghost** [comment]
Sir

I have replied to your mail sir.

Kindly check it and do the needful.

Regards
Guna

**Comment by philipp-eger-dev** [comment]
Problem fixed per Mail
